ACookingKitchen/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from category import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # CATEGORY
    path('category/create', views.CreateCategory.as_view(), name='create_category'),
    path('category/<int:pk>', views.DetailCategory.as_view(), name='detail_category'),
    path('category/<int:pk>/update', views.UpdateCategory.as_view(), name='update_category'),
    path('category/<int:pk>/delete', views.DeleteCategory.as_view(), name='delete_category'),
    # Recipes
    path('category/<int:pk>/addrecipe', views.add_recipe, name='add_recipe'),
    path('recipe/<int:pk>', views.DetailRecipe.as_view(), name='detail_recipe'),
    path('recipe/<int:pk>/update', views.UpdateRecipe.as_view(), name='update_recipe'),
    path('recipe/<int:pk>/delete', views.DeleteRecipe.as_view(), name='delete_recipe')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

category/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Recipe(models.Model):
    title = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='recipe/images/', blank=True)
    prep_time = models.CharField(max_length=100)
    cook_time = models.CharField(max_length=100)
    servings = models.IntegerField(blank=True)
    ingredients = models.TextField()
    directions = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

category/forms.py
from .models import Recipe
from django import forms

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'picture', 'prep_time', 'cook_time', 'servings', 'ingredients', 'directions', ]
        labels = {'cook_time': 'Cook Time'}

category/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import Category, Recipe
from .forms import RecipeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


def home(request):
    recent_categories = Category.objects.all().order_by('-id')[:3]
    popular_categories = [Category.objects.get(pk=1)], [Category.objects.get(pk=2)], [Category.objects.get(pk=3)],
    return render(request, 'category/home.html', {'recent_categories': recent_categories,
                                                  'popular_categories': popular_categories})


@login_required
def dashboard(request):
    categories = Category.objects.filter(user=request.user)
    return render(request, 'category/dashboard.html', {'categories': categories})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class CreateCategory(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = ['title']
    template_name = 'category/create_category.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateCategory, self).form_valid(form)
        return redirect('dashboard')


class DetailCategory(generic.DetailView):
    model = Category
    template_name = 'category/detail_category.html'


class DetailRecipe(generic.DetailView):
    model = Recipe
    template_name = 'category/detail_recipe.html'


class UpdateCategory(LoginRequiredMixin, generic.UpdateView):
    model = Category
    template_name = 'category/update_category.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self, queryset=None):
        category = super(UpdateCategory, self).get_object()
        if not category.user == self.request.user:
            raise Http404
        return category



class UpdateRecipe(LoginRequiredMixin, generic.UpdateView):
    model = Recipe
    template_name = 'category/update_recipe.html'
    fields = ['title', 'prep_time', 'cook_time', 'servings', 'ingredients', 'directions']
    success_url = reverse_lazy('dashboard')

    def get_object(self, queryset=None):
        recipe = super(UpdateRecipe, self).get_object()
        if not recipe.category.user == self.request.user:
            raise Http404
        return recipe


class DeleteCategory(LoginRequiredMixin, generic.DeleteView):
    model = Category
    template_name = 'category/delete_category.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self, queryset=None):
        cat = super(DeleteCategory, self).get_object()
        if not cat.user == self.request.user:
            raise Http404
        return cat


class DeleteRecipe(LoginRequiredMixin, generic.DeleteView):
    model = Recipe
    template_name = 'category/delete_recipe.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self, queryset=None):
        recipe = super(DeleteRecipe, self).get_object()
        if not recipe.category.user == self.request.user:
            raise Http404
        return recipe


@login_required
def add_recipe(request, pk):
    form = RecipeForm()
    cat = Category.objects.get(pk=pk)
    if not cat.user == request.user:
        raise Http404
    if request.method == 'POST':
        done_form = RecipeForm(request.POST)
        if done_form.is_valid():
            recipe = Recipe()
            recipe.category = cat
            recipe.title = done_form.cleaned_data['title']
            recipe.picture = done_form.instance
            recipe.prep_time = done_form.cleaned_data['prep_time']
            recipe.cook_time = done_form.cleaned_data['cook_time']
            recipe.servings = done_form.cleaned_data['servings']
            recipe.ingredients = done_form.cleaned_data['ingredients']
            recipe.directions = done_form.cleaned_data['directions']
            recipe.category = Category.objects.get(pk=pk)
            recipe.save()
            return redirect('detail_category', pk)

    return render(request, 'category/add_recipe.html', {'form': form})

category/templates/category/add_recipe.html
{% extends 'category/base.html' %}

{% block content %}

  <div class="container">
  <h2>Add personal Recipe</h2>
  <h3>End each line by hitting enter when entering ingredients and directions</h3>
      <form method="post">
          {% csrf_token %}
            {% load widget_tweaks %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class='form-control' %}
                </div>
            {% endfor %}

          <button type="submit"  class="btn btn-primary">Create</button>
      </form>
  </div>


{% endblock %}

category/templates/category/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link href="{% static 'custom.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Arri's Cooking Kitchen</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
      {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
      {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
    <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>

</html>

category/templates/category/create_category.html
{% extends 'category/base.html' %}

{% block content %}

    <div class="container">
        <h2>Make a category or theme of recipes you'd like to add to</h2>
        <form method="post">
            {% csrf_token %}
            {% load widget_tweaks %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class='form-control' %}
                </div>
            {% endfor %}

            <button type="submit" value="Create" class="btn btn-primary">Create</button>
        </form>
    </div>

{% endblock %}

category/templates/category/dashboard.html
{% extends 'category/base.html' %}

{% block content %}

    <div class="container">
        <div class="text-center">
            <h1>{{ user.username }}'s Recipes</h1>
            <a href="{% url 'create_category' %}" class="btn btn-primary"> Create new category for recipes</a>

        </div>
    <br>
        <div class="text-center"><h4><strong>To edit a recipe click on the category it belongs to</strong></h4></div>


        {% for item in categories %}

            <h2> <a href="{% url 'detail_category' item.id %}">{{ item.title }}</a> </h2>
            <a href="{% url 'delete_category' item.id %}" class="btn btn-danger"> Delete</a>
            <a href="{% url 'update_category' item.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'add_recipe' item.id %}" class="btn btn-primary"> Add Recipe</a>

            <div class="row">
                {% for res in item.recipe_set.all %}

                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-body">
                                <p class="card-text">{{ res.title }}</p>
                                <p class="card-text">{{ res.picture }}</p>
                                <a href="{% url 'detail_recipe' res.id %}">Recipe</a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        {% endfor %}

    </div>


{% endblock %}

category/templates/category/delete_category.html
{% extends 'category/base.html' %}

{% block content %}

  <div class="container">
  <h2>Are you sure you want to delete this category</h2>
      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit"  class="btn btn-danger">Delete</button>
      </form>
      <br>

 <h2><a href="{% url 'detail_category' category.id %}">{{ category.title }}</a></h2>
  </div>

{% endblock %}

category/templates/category/delete_recipe.html
{% extends 'category/base.html' %}

{% block content %}

  <div class="container">
  <h2>Are you sure you want to delete this recipe</h2>
      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit"  class="btn btn-danger">Delete</button>
      </form>
      <br>

    {{ recipe.title }}
    {{ recipe.picture }}
  </div>

{% endblock %}

category/templates/category/detail_category.html
{% extends 'category/base.html' %}

{% block content %}

  <div class="container">
  <h1>{{ category.title }}</h1>
  <h4 class="text-muted">{{ category.user.username }}</h4>


  {% if user.id == category.user.id %}
            <a href="{% url 'delete_category' category.id %}" class="btn btn-danger"> Delete</a>
            <a href="{% url 'update_category' category.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'add_recipe' category.id %}" class="btn btn-primary">Add</a>
{% endif %}
   <h3>If editing at the end of steps add a space by entering a line break at the end of ingredients and directions</h3>
            <div class="row">
                {% for res in category.recipe_set.all %}


                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-body">
                                <p><a href="{% url 'detail_recipe' res.id %}">{{ res.title }}</a></p>

                                <br>
                                <br>
                                {% if user.id == category.user.id %}
                                    <a href="{% url 'delete_recipe' res.id %}" class="btn btn-danger"> Delete </a>
                                    <a href="{% url 'update_recipe' res.id %}" class="btn btn-warning"> Edit </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>


  </div>

{% endblock %}

category/templates/category/detail_recipe.html
{% extends 'category/base.html' %}

{% block content %}
<br>

  <div class="container">

      <h1>{{ recipe.title }}</h1>

{#      {% if recipe.picture %}#}
{#      <h3><img src="{{ recipe.images }}" alt="{{ recipe.title }}"></h3>#}
{#      {% endif %}#}

       <br>
      <h6>Servings: {{ recipe.servings }}</h6>
       <br>
      <h5><strong><u><i>Prep Time: {{ recipe.prep_time }}</i></u></strong></h5>
       <br>
      <h4><strong><u>Ingredients</u>:</strong> {{ recipe.ingredients|linebreaks }}</h4>
       <br>
      <h5><strong><u><i>Cook Time: {{ recipe.cook_time }}</i></u></strong></h5>
       <br>
      <h4><strong><u>Directions</u>:</strong> {{ recipe.directions|linebreaks }}</h4>
       <br>
  <h4 class="text-muted">{{ category.user }}</h4>
  </div>
      <a href="{% url 'home' %}" class="btn btn-primary">Home</a>
{% endblock %}

category/templates/category/home.html
{% extends 'category/base.html' %}
{% load static %}

{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Find and Share Favorite Recipes! </h1>
            <p class="lead text-muted">Cooking is fantastic, but its better when we share the food we love with people
                who enjoy it. Click below to get started</p>
            <p>
                <a href="{% url 'create_category' %}" class="btn btn-primary"> Create your food category</a>
            </p>
        </div>
    </section>

    <div class="container">
        <h1 class="text-center">Popular Categories</h1>
        <br>
        <div class="row">
            <div class="row col-6">
                {% for item in popular_categories %}
                    {% for res in item %}
                        <div class="col-md-6 mt-3">
                            <div class="card mb-6 shadow-sm">
                                <div class="card-body">

                                    <p class="card-text">{{ res.picture }}</p>
                                    <p class="card-text">{{ res.user }}'s {{ res.title }} recipes</p>
                                    <a href="{% url 'detail_category' res.id %}"><p class="card-text">{{ res.title }}</p></a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                {% endfor %}
            </div>

            <div class="col-md-6 mt-3">

                <div class="card mb-6 shadow-sm">
                    <div class="card-body">
                        <img src="{% static 'pic2.jpg' %}" class="img-fluid" alt="wok">
                    </div>
                </div>
            </div>
        </div>

        <br>
        <br>

        <h1 class="text-center">Recent Categories</h1>
        <br>

        <div class="row">
            <div class="col-md-6 mt-3">
                <div class="card mb-6 shadow-sm">
                    <div class="card-body">
                        <img src="{% static 'pic1.jpg' %}" class="img-fluid" alt="cutting board">
                    </div>
                </div>
            </div>
            <div class="row col-6">
                {% for item in recent_categories %}
                    <div class="col-md-6 mt-3">
                        <div class="card mb-6 shadow-sm">
                            <div class="card-body">
                                <p class="card-text">{{ item.picture }}</p>
                                <p class="card-text">{{ item.user }}'s {{ item.title }} recipes</p>
                                <a href="{% url 'detail_category' item.id %}"><p class="card-text">{{ item.title }}</p></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}

category/templates/category/update_category.html
{% extends 'category/base.html' %}

{% block content %}

  <div class="container">
  <h2>Edit</h2>
      <form method="post">
          {% csrf_token %}
           {% load widget_tweaks %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class='form-control' %}
                </div>
            {% endfor %}
          <button type="submit"  class="btn btn-primary">Save</button>
      </form>
  <br>
  <a href="{% url 'delete_category' category.id %}" class="btn btn-danger">Delete Category</a>
  </div>

{% endblock %}

category/templates/category/update_recipe.html
{% extends 'category/base.html' %}

{% block content %}

  <div class="container">
  <h2>Edit</h2>
      <form method="post">
          {% csrf_token %}
           {% load widget_tweaks %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class='form-control' %}
                </div>
            {% endfor %}
          <button type="submit"  class="btn btn-primary">Save</button>
      </form>
  <br>

  </div>

{% endblock %}